/**
 * Track 5 #5 — PIREP-Logbook PDF document.
 *
 * Single-page A4 debrief-sheet das alle wichtigen flight-metrics
 * eines PIREPs in print-ready form rendert. Renderable serverside
 * via @react-pdf/renderer.renderToStream().
 *
 * # Why a PDF (and not screenshot or HTML-print)
 *
 * - Pilots wollen ein "echtes" logbook-document zum archivieren —
 *   nicht eine HTML-page die je nach browser anders aussieht
 * - Konstantes A4-layout, vorhersagbare seitenränder
 * - Email-fähig, druckbar, embed-bar in flight-portfolios
 * - Print-style-rules in HTML sind brittle (jeder browser interpretiert
 *   sie anders); @react-pdf/renderer gibt deterministischen output
 *
 * # Layout (top to bottom)
 *
 * 1. Header-band: Airline-name + PIREP-id + flight-number + date
 * 2. Route-strip: ICAO → ICAO mit airport-namen darunter
 * 3. Hero-KPIs (4-col grid): Block-time, Distance, Fuel, Smoothness
 * 4. Pilot + Aircraft (2-col)
 * 5. Approach + Landing metrics (3-col grid wenn data available)
 * 6. Auto-Suggestions (wenn vorhanden) — bullet-list, color-coded
 * 7. Footer: "generated by VAM-System" + ISO-timestamp
 *
 * NICHT included (V1 cutoff):
 * - Map/trail-visualization (würde clientside-screenshot oder static-map-API brauchen)
 * - Charts (vertical-profile, IAS/VSI) — recharts läuft nicht in @react-pdf
 * - Annotations (Track 5 #3) — könnte als appendix-page; V1 single-page
 *
 * # Font-strategy
 *
 * Standard PDF fonts ohne external-font-fetches: Helvetica (sans-serif)
 * für body, Courier (mono) für ICAO/registrations/numeric data. Beide
 * sind PDF-base-14 fonts, kein download nötig, kein bundling-overhead.
 * (Vermeidet das @react-pdf font-registration drama mit unicode-ranges
 * und woff-fetches die in serverless-environments oft fail'n.)
 */

import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import type {
  Suggestion,
  SuggestionSeverity,
} from './pirep-metrics';

// ─────────────────────────────────────────────────────────────────────
// Types — what the API-route passes in. Mirrors the detail-page shape
// loosely; nullables tolerated everywhere so manual-PIREPs ohne ACARS-
// data noch rendern.
// ─────────────────────────────────────────────────────────────────────

export type LogbookData = {
  pirep: {
    id: string;
    submittedAt: Date;
    status: string;
    flightTimeMin: number | null;
    fuelUsedKg: number | null;
    landingRateFpm: number | null;
    passengerCount: number | null;
    cargoKg: number | null;
    remarks: string | null;
  };
  airline: { name: string; icao: string | null };
  route: {
    flightNumber: string | null;
    distanceNm: number | null;
  };
  departure: {
    icao: string;
    name: string;
    city: string | null;
  };
  arrival: {
    icao: string;
    name: string;
    city: string | null;
  };
  pilot: {
    name: string | null;
    rankName: string | null;
  };
  aircraft: {
    registration: string;
    type: string;
  } | null;
  approach: {
    iasAt1000ft: number | null;
    glideslopeQualityPercent: number | null;
    stabilizationScorePercent: number | null;
  } | null;
  landing: {
    verticalFpmAtTouchdown: number | null;
    groundSpeedKtsAtTouchdown: number | null;
    altitudeAglAtTouchdown: number | null;
    atIcao: string | null;
  } | null;
  smoothnessScore: number | null;
  suggestions: Suggestion[];
};

// ─────────────────────────────────────────────────────────────────────
// Styles — mirrors the on-page card-styling but with print-safe colors
// (avoid background-tints on cards — they don't print well; use borders
// instead).
// ─────────────────────────────────────────────────────────────────────

const COLORS = {
  ink: '#111111',
  text: '#333333',
  muted: '#666666',
  faint: '#999999',
  border: '#cccccc',
  borderBold: '#999999',
  indigo: '#4f46e5',
  green: '#16a34a',
  amber: '#d97706',
  red: '#dc2626',
  blue: '#2563eb',
};

const styles = StyleSheet.create({
  page: {
    paddingTop: 28,
    paddingHorizontal: 32,
    paddingBottom: 32,
    fontFamily: 'Helvetica',
    fontSize: 9,
    color: COLORS.text,
  },

  // ─── Header ───
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: 2,
    borderBottomColor: COLORS.ink,
    paddingBottom: 8,
    marginBottom: 12,
  },
  headerLeft: { flexDirection: 'column' },
  airlineName: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.ink,
  },
  headerSubtitle: {
    fontSize: 8,
    color: COLORS.muted,
    marginTop: 2,
  },
  headerRight: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  flightNumber: {
    fontSize: 14,
    fontFamily: 'Courier-Bold',
    color: COLORS.indigo,
  },
  pirepDate: {
    fontSize: 8,
    color: COLORS.muted,
    marginTop: 2,
  },

  // ─── Route strip ───
  routeStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: COLORS.borderBold,
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  routeAirport: { flexDirection: 'column', alignItems: 'center', flex: 1 },
  routeIcao: {
    fontSize: 22,
    fontFamily: 'Courier-Bold',
    color: COLORS.ink,
  },
  routeAirportName: {
    fontSize: 8,
    color: COLORS.muted,
    marginTop: 3,
    textAlign: 'center',
  },
  routeArrow: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  routeArrowGlyph: {
    fontSize: 14,
    color: COLORS.muted,
  },
  routeDistance: {
    fontSize: 9,
    color: COLORS.text,
    marginTop: 2,
    fontFamily: 'Courier',
  },

  // ─── KPI cards grid ───
  kpiGrid: {
    flexDirection: 'row',
    marginBottom: 12,
    gap: 6,
  },
  kpiCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  kpiLabel: {
    fontSize: 7,
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontFamily: 'Helvetica-Bold',
  },
  kpiValue: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.ink,
    marginTop: 4,
  },
  kpiUnit: {
    fontSize: 9,
    fontFamily: 'Helvetica',
    color: COLORS.muted,
  },
  kpiSub: {
    fontSize: 7,
    color: COLORS.muted,
    marginTop: 2,
  },

  // ─── 2-col section (pilot + aircraft) ───
  twoCol: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  sectionCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  sectionLabel: {
    fontSize: 7,
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
  },
  sectionValue: {
    fontSize: 11,
    color: COLORS.ink,
    fontFamily: 'Helvetica-Bold',
  },
  sectionSub: {
    fontSize: 8,
    color: COLORS.muted,
    marginTop: 2,
  },

  // ─── 3-col approach/landing metrics ───
  threeCol: { flexDirection: 'row', gap: 6, marginBottom: 12 },

  // ─── Suggestions ───
  suggestionBox: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 12,
  },
  suggestionTitle: {
    fontSize: 7,
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 6,
  },
  suggestionItem: {
    flexDirection: 'row',
    marginTop: 4,
  },
  suggestionBullet: {
    fontFamily: 'Helvetica-Bold',
    marginRight: 5,
    width: 10,
  },
  suggestionBody: { flex: 1 },
  suggestionTitleText: {
    fontFamily: 'Helvetica-Bold',
    color: COLORS.ink,
    fontSize: 9,
  },
  suggestionDetail: {
    color: COLORS.muted,
    fontSize: 8,
    marginTop: 1,
  },

  // ─── Remarks ───
  remarksBox: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 12,
  },
  remarksText: {
    fontSize: 9,
    color: COLORS.text,
    marginTop: 4,
  },

  // ─── Footer ───
  footer: {
    position: 'absolute',
    bottom: 16,
    left: 32,
    right: 32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 7,
    color: COLORS.faint,
    borderTopWidth: 0.5,
    borderTopColor: COLORS.border,
    paddingTop: 6,
  },
});

// ─────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────

function severityColor(s: SuggestionSeverity): string {
  return s === 'warning' ? COLORS.amber : COLORS.blue;
}

function severityGlyph(s: SuggestionSeverity): string {
  return s === 'warning' ? '!' : 'i';
}

function smoothnessColor(score: number): string {
  if (score >= 85) return COLORS.green;
  if (score >= 70) return COLORS.green;
  if (score >= 55) return COLORS.amber;
  if (score >= 40) return COLORS.amber;
  return COLORS.red;
}

function smoothnessLabel(score: number): string {
  if (score >= 85) return 'excellent';
  if (score >= 70) return 'good';
  if (score >= 55) return 'acceptable';
  if (score >= 40) return 'needs work';
  return 'rough';
}

function formatFlightTime(min: number | null): string {
  if (min === null) return '—';
  const h = Math.floor(min / 60);
  const m = min % 60;
  if (h > 0) return `${h}h ${m}m`;
  return `${m}m`;
}

// ─────────────────────────────────────────────────────────────────────
// Document
// ─────────────────────────────────────────────────────────────────────

export function PirepLogbookPdf({ data }: { data: LogbookData }) {
  const {
    pirep,
    airline,
    route,
    departure,
    arrival,
    pilot,
    aircraft,
    approach,
    landing,
    smoothnessScore,
    suggestions,
  } = data;

  // Touchdown-VSI severity helpers — same logic as detail-page Landing
  // section but inline (no shared helper, klein genug).
  const tdVsi =
    landing?.verticalFpmAtTouchdown !== null &&
    landing?.verticalFpmAtTouchdown !== undefined
      ? Math.abs(landing.verticalFpmAtTouchdown)
      : null;
  const tdSeverity =
    tdVsi === null
      ? '—'
      : tdVsi < 200
        ? 'smooth'
        : tdVsi < 400
          ? 'normal'
          : tdVsi < 600
            ? 'firm'
            : tdVsi < 1000
              ? 'hard'
              : 'severe';

  return (
    <Document
      title={`Logbook ${route.flightNumber ?? 'PIREP'} ${departure.icao}-${arrival.icao}`}
      author={airline.name}
      subject="PIREP Logbook"
      creator="VAM-System"
    >
      <Page size="A4" style={styles.page}>
        {/* ───── Header ───── */}
        <View style={styles.header}>
          <View style={styles.headerLeft}>
            <Text style={styles.airlineName}>{airline.name}</Text>
            <Text style={styles.headerSubtitle}>
              {airline.icao ? `${airline.icao} · ` : ''}Pilot Logbook
            </Text>
          </View>
          <View style={styles.headerRight}>
            <Text style={styles.flightNumber}>
              {route.flightNumber ?? 'PIREP'}
            </Text>
            <Text style={styles.pirepDate}>
              {pirep.submittedAt.toLocaleString('de-DE', {
                dateStyle: 'long',
                timeStyle: 'short',
              })}
            </Text>
            <Text style={styles.pirepDate}>Status: {pirep.status}</Text>
          </View>
        </View>

        {/* ───── Route strip ───── */}
        <View style={styles.routeStrip}>
          <View style={styles.routeAirport}>
            <Text style={styles.routeIcao}>{departure.icao}</Text>
            <Text style={styles.routeAirportName}>
              {departure.name}
              {departure.city ? `\n${departure.city}` : ''}
            </Text>
          </View>
          <View style={styles.routeArrow}>
            <Text style={styles.routeArrowGlyph}>→</Text>
            <Text style={styles.routeDistance}>
              {route.distanceNm !== null ? `${route.distanceNm} nm` : '— nm'}
            </Text>
          </View>
          <View style={styles.routeAirport}>
            <Text style={styles.routeIcao}>{arrival.icao}</Text>
            <Text style={styles.routeAirportName}>
              {arrival.name}
              {arrival.city ? `\n${arrival.city}` : ''}
            </Text>
          </View>
        </View>

        {/* ───── KPI grid: Block-Time, Fuel, Pax, Smoothness ───── */}
        <View style={styles.kpiGrid}>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Block-Time</Text>
            <Text style={styles.kpiValue}>
              {formatFlightTime(pirep.flightTimeMin)}
            </Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Treibstoff</Text>
            <Text style={styles.kpiValue}>
              {pirep.fuelUsedKg !== null ? `${pirep.fuelUsedKg}` : '—'}
              {pirep.fuelUsedKg !== null && (
                <Text style={styles.kpiUnit}> kg</Text>
              )}
            </Text>
          </View>
          <View style={styles.kpiCard}>
            <Text style={styles.kpiLabel}>Passagiere</Text>
            <Text style={styles.kpiValue}>
              {pirep.passengerCount !== null ? pirep.passengerCount : '—'}
            </Text>
            {pirep.cargoKg !== null && pirep.cargoKg > 0 && (
              <Text style={styles.kpiSub}>+{pirep.cargoKg} kg Cargo</Text>
            )}
          </View>
          <View
            style={[
              styles.kpiCard,
              smoothnessScore !== null
                ? { borderColor: smoothnessColor(smoothnessScore) }
                : {},
            ]}
          >
            <Text style={styles.kpiLabel}>Smoothness</Text>
            {smoothnessScore !== null ? (
              <>
                <Text
                  style={[
                    styles.kpiValue,
                    { color: smoothnessColor(smoothnessScore) },
                  ]}
                >
                  {smoothnessScore}
                  <Text style={styles.kpiUnit}> /100</Text>
                </Text>
                <Text style={styles.kpiSub}>
                  {smoothnessLabel(smoothnessScore)}
                </Text>
              </>
            ) : (
              <>
                <Text style={[styles.kpiValue, { color: COLORS.faint }]}>—</Text>
                <Text style={styles.kpiSub}>keine ACARS-daten</Text>
              </>
            )}
          </View>
        </View>

        {/* ───── Pilot + Aircraft ───── */}
        <View style={styles.twoCol}>
          <View style={styles.sectionCard}>
            <Text style={styles.sectionLabel}>Pilot</Text>
            <Text style={styles.sectionValue}>
              {pilot.name ?? 'Unbenannt'}
            </Text>
            <Text style={styles.sectionSub}>
              {pilot.rankName ?? 'Kein Rang'}
            </Text>
          </View>
          <View style={styles.sectionCard}>
            <Text style={styles.sectionLabel}>Aircraft</Text>
            {aircraft ? (
              <>
                <Text style={[styles.sectionValue, { fontFamily: 'Courier-Bold' }]}>
                  {aircraft.registration}
                </Text>
                <Text style={styles.sectionSub}>{aircraft.type}</Text>
              </>
            ) : (
              <Text style={styles.sectionValue}>—</Text>
            )}
          </View>
        </View>

        {/* ───── Approach metrics (wenn data) ───── */}
        {approach &&
          (approach.iasAt1000ft !== null ||
            approach.glideslopeQualityPercent !== null ||
            approach.stabilizationScorePercent !== null) && (
            <View style={styles.threeCol}>
              <View style={styles.sectionCard}>
                <Text style={styles.sectionLabel}>IAS @ 1000ft AGL</Text>
                <Text style={styles.sectionValue}>
                  {approach.iasAt1000ft !== null
                    ? `${approach.iasAt1000ft} kt`
                    : '—'}
                </Text>
              </View>
              <View style={styles.sectionCard}>
                <Text style={styles.sectionLabel}>Glideslope (3°)</Text>
                <Text style={styles.sectionValue}>
                  {approach.glideslopeQualityPercent !== null
                    ? `${approach.glideslopeQualityPercent.toFixed(0)}%`
                    : '—'}
                </Text>
              </View>
              <View style={styles.sectionCard}>
                <Text style={styles.sectionLabel}>Stabilized</Text>
                <Text style={styles.sectionValue}>
                  {approach.stabilizationScorePercent !== null
                    ? `${approach.stabilizationScorePercent.toFixed(0)}%`
                    : '—'}
                </Text>
              </View>
            </View>
          )}

        {/* ───── Landing metrics (wenn data) ───── */}
        {landing && landing.verticalFpmAtTouchdown !== null && (
          <View style={styles.threeCol}>
            <View style={styles.sectionCard}>
              <Text style={styles.sectionLabel}>Touchdown-Rate</Text>
              <Text style={styles.sectionValue}>
                {tdVsi !== null ? `${tdVsi} fpm` : '—'}
              </Text>
              <Text style={styles.sectionSub}>{tdSeverity}</Text>
            </View>
            <View style={styles.sectionCard}>
              <Text style={styles.sectionLabel}>Groundspeed</Text>
              <Text style={styles.sectionValue}>
                {landing.groundSpeedKtsAtTouchdown !== null
                  ? `${landing.groundSpeedKtsAtTouchdown} kt`
                  : '—'}
              </Text>
              {landing.altitudeAglAtTouchdown !== null && (
                <Text style={styles.sectionSub}>
                  @ {landing.altitudeAglAtTouchdown}ft AGL
                </Text>
              )}
            </View>
            <View style={styles.sectionCard}>
              <Text style={styles.sectionLabel}>Touchdown @</Text>
              <Text style={[styles.sectionValue, { fontFamily: 'Courier-Bold' }]}>
                {landing.atIcao ?? '—'}
              </Text>
              {landing.atIcao && landing.atIcao !== arrival.icao && (
                <Text style={[styles.sectionSub, { color: COLORS.amber }]}>
                  ≠ Arrival ({arrival.icao})
                </Text>
              )}
            </View>
          </View>
        )}

        {/* ───── Suggestions ───── */}
        {suggestions.length > 0 && (
          <View style={styles.suggestionBox}>
            <Text style={styles.suggestionTitle}>
              Verbesserungshinweise ({suggestions.length})
            </Text>
            {suggestions.map((s, idx) => (
              <View key={idx} style={styles.suggestionItem}>
                <Text
                  style={[
                    styles.suggestionBullet,
                    { color: severityColor(s.severity) },
                  ]}
                >
                  {severityGlyph(s.severity)}
                </Text>
                <View style={styles.suggestionBody}>
                  <Text style={styles.suggestionTitleText}>{s.title}</Text>
                  {s.detail && (
                    <Text style={styles.suggestionDetail}>{s.detail}</Text>
                  )}
                </View>
              </View>
            ))}
          </View>
        )}

        {/* ───── Remarks ───── */}
        {pirep.remarks && pirep.remarks.trim().length > 0 && (
          <View style={styles.remarksBox}>
            <Text style={styles.sectionLabel}>Bemerkungen</Text>
            <Text style={styles.remarksText}>{pirep.remarks}</Text>
          </View>
        )}

        {/* ───── Footer ───── */}
        <View style={styles.footer}>
          <Text>VAM-System · Pilot Logbook · PIREP {pirep.id}</Text>
          <Text>
            Generated{' '}
            {new Date().toLocaleString('de-DE', {
              dateStyle: 'short',
              timeStyle: 'short',
            })}
          </Text>
        </View>
      </Page>
    </Document>
  );
}
